image: ubuntu:latest
stages:
  - Scan Early
  - Lint
  - Build
  - Scan
  - Test
  - Release
  - GitLab
before_script:
  - apt-get update && apt-get install -y python3 python3-venv
variables:
  REGISTRY: registry.gitlab.com/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  IMAGE_TARBALL: container-$CI_COMMIT_SHORT_SHA.tar
  IMAGE_TAG: $REGISTRY:$CI_COMMIT_SHORT_SHA
  IMAGE_TAG_RELEASE: $REGISTRY:$CI_COMMIT_TAG
  IMAGE_TAG_BLEEDING: $REGISTRY:bleeding
  IMAGE_TAG_LATEST: $REGISTRY:latest
default:
  interruptible: yes
  retry: 2
  services:
    - name: docker:dind
      alias: docker
      command: ["--tls=false"]
  cache:
    - key: cache-venv-$CI_COMMIT_REF_SLUG
      paths:
        - venv
    - key: trivy-db
      paths:
        - .trivy
# Lightweight scanning where we check for repo misconfigs
Trivy Secrets:
  image:
    name: aquasec/trivy
    entrypoint: [""]
  stage: Scan Early
  retry: 0
  script:
    - trivy fs
        --exit-code 1
        ./
Trivy Misconfiguration:
  image:
    name: aquasec/trivy
    entrypoint: [""]
  stage: Scan Early
  retry: 0
  script:
    - trivy config
        --severity HIGH,CRITICAL
        --exit-code 1
        ./

# Linting and preprocessing
# All of these should be required for PRs and run on all branches
Black:
  stage: Lint
  script:
    - python3 -m venv venv
    - . venv/bin/activate
    - pip3 install --upgrade pip
    - pip3 install --upgrade -r requirements.txt -r requirements-build.txt
    - python3 -m black --check .
isort:
  stage: Lint
  script:
    - python3 -m venv venv
    - . venv/bin/activate
    - pip3 install --upgrade pip
    - pip3 install --upgrade -r requirements.txt -r requirements-build.txt
    - python3 -m isort --profile black --check-only .
YAML Lint:
  stage: Lint
  image:
    name: ghcr.io/google/yamlfmt:latest
    entrypoint: [""]
  cache: []
  before_script:
    - apk add git
  script:
    - echo "Formatting..."
    - yamlfmt
    - git diff --exit-code
    - echo "Formatting complete"
# Building
Build Container:
  image: docker:latest
  cache: []
  before_script: []
  stage: Build
  script:
    # Basic Docker setup
    - docker --version
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $REGISTRY
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
    # Set up build environment
    - docker buildx create --use
    - docker buildx inspect --bootstrap
    # Build the container
    - docker buildx build
        --platform linux/amd64,linux/arm64
        --build-arg commit_sha=$CI_COMMIT_SHORT_SHA
        --build-arg commit_tag=$CI_COMMIT_TAG
        --tag=$IMAGE_TAG
        --output type=oci,dest=$IMAGE_TARBALL
        .
    # Last-minute debug info
    - docker images
  artifacts:
    paths:
      - $IMAGE_TARBALL
    expire_in: 1h
# The real meaty scanning where we check for package vulns
Scan Container:
  image:
    name: aquasec/trivy
    entrypoint: [""]
  stage: Scan
  allow_failure: true
  retry: 0
  before_script:
    - mkdir container
    - tar xf $IMAGE_TARBALL -C container
  script:
    - trivy image
        --input container
        --platform linux/amd64
        --scanners vuln,secret,misconfig
        --severity HIGH,CRITICAL
        --ignore-unfixed
        --exit-code 1
    - trivy image
        --input container
        --platform linux/arm64
        --scanners vuln,secret,misconfig
        --severity HIGH,CRITICAL
        --ignore-unfixed
        --exit-code 1
# Tagging
Tag SHA:
  image:
    name: quay.io/containers/skopeo:latest
    entrypoint: [""]
  interruptible: no
  cache: []
  before_script: []
  stage: Release
  script:
    - echo "$CI_REGISTRY_PASSWORD" | skopeo login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
    - skopeo inspect oci-archive:$IMAGE_TARBALL
    - skopeo copy --all oci-archive:$IMAGE_TARBALL docker://$IMAGE_TAG
    - skopeo copy --all oci-archive:$IMAGE_TARBALL docker://$IMAGE_TAG_BLEEDING
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_TAG
Tag Release:
  image:
    name: quay.io/containers/skopeo:latest
    entrypoint: [""]
  interruptible: no
  cache: []
  before_script: []
  stage: Release
  script:
    - echo "$CI_REGISTRY_PASSWORD" | skopeo login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
    - skopeo inspect oci-archive:$IMAGE_TARBALL
    - skopeo copy --all oci-archive:$IMAGE_TARBALL docker://$IMAGE_TAG_RELEASE
    - skopeo copy --all oci-archive:$IMAGE_TARBALL docker://$IMAGE_TAG_LATEST
  rules:
    - if: $CI_COMMIT_TAG
Release:
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  interruptible: no
  cache: []
  before_script: []
  stage: GitLab
  script:
    - echo "Running release job..."
  rules:
    - if: $CI_COMMIT_TAG
  release:
    tag_name: $CI_COMMIT_TAG
    name: "GunCAD Mirror - $CI_COMMIT_TAG"
    description: $CI_COMMIT_TAG_MESSAGE
