---
services:
  guncad-mirror:
    image: "${MIRROR_IMAGE:-registry.gitlab.com/guncad-index/mirror:latest}"
    stop_grace_period: 2m
    env_file: "${MIRROR_ENV_FILE:-guncad-mirror.env}"
    volumes:
      - guncad-mirror:/data:Z
    ports:
      # LBRY uses this port to serve rehosted content. If not exposed, you're
      # just leeching.
      - 5567:5567/tcp
      # This is to participate in the DHT. Needs both TCP and UDP
      - 4444:4444/tcp
      - 4444:4444/udp
      # This is for the web UI. You can omit if you don't want it
      - 8081:5000/tcp
    healthcheck:
      test: |
        curl -f http://127.0.0.1:5279 -X POST -d '{"method": "status"}' | grep -ie '^.*is_running.*true.*$' || exit 1
      start_period: 300s
      interval: 5s
      timeout: 15s
      retries: 12
volumes:
  guncad-mirror:
    name: "${MIRROR_DATA_VOLUME:-guncad-mirror}"
