version: "3.8"
services:
  guncad-mirror:
    build: .
    env_file: guncad-mirror.env
    command:
      - "-v"
    volumes:
      - guncad-mirror:/data:Z
    ports:
      # LBRY uses this port to serve rehosted content. If not exposed, you're
      # just leeching.
      - 5567:5567/tcp
    healthcheck:
      test: |
        curl -f http://127.0.0.1:5279 -X POST -d '{"method": "status"}' | grep -ie '^.*is_running.*true.*$' || exit 1
      interval: 5s
      timeout: 15s
      retries: 3

volumes:
  guncad-mirror:
