ARG qbittorrent_image=docker.io/qbittorrentofficial/qbittorrent-nox:5.2.3-1
FROM ${qbittorrent_image}

COPY --chmod=755 contrib/qbittorrent-entrypoint.py /usr/local/bin/start-guncad-qbittorrent

ENTRYPOINT ["/sbin/tini", "-g", "--", "/usr/local/bin/start-guncad-qbittorrent"]
